dist: trusty
language: node_js
node_js:
- stable
branches:
   only: development
notifications:
   email:
      recipients:
      - 645372879@qq.com      # change to your own address
      - Nuist_Bj@163.com    # uae other (optional)
      on_success: never        # default: change
      on_failure: always       # default: always